package com.example.plantbot.domain;

public enum AiRequestKind {
  PLANT_PROFILE_LOOKUP,
  PLANT_CARE_ADVICE,
  PLANT_WATERING_PROFILE,
  WIZARD_RECOMMENDATION,
  SEED_RECOMMENDATION,
  PLANT_SEARCH,
  ASSISTANT_CHAT,
  PHOTO_IDENTIFY,
  PHOTO_DIAGNOSIS,
  GROWTH_SUMMARY,
  AVATAR_SPEC,
  MODEL_HEALTH_CHECK,
  ADMIN_TEST,
  ADMIN_PROVIDER_TEST_CONNECTION,
  ADMIN_PROVIDER_TEST_JSON,
  ADMIN_PROVIDER_TEST_VISION,
  OTHER_AI_REQUEST
}
