package com.example.plantbot.domain;

public enum AiTextFeatureType {
  PLANT_CARE_ADVICE,
  PLANT_WATERING_PROFILE_AI,
  WIZARD_WATERING_RECOMMENDATION,
  PLANT_AI_RECOMMEND_LEGACY,
  SEED_RECOMMENDATION,
  PLANT_SEARCH_SUGGESTIONS_AI,
  PLANT_DIAGNOSIS_TEXT,
  PLANT_IDENTIFY_TEXT,
  AI_CHAT_TEXT
}
