package com.example.plantbot.controller.dto;

import com.example.plantbot.domain.OutdoorSoilType;
import com.example.plantbot.domain.PlantCategory;
import com.example.plantbot.domain.PlantContainerType;
import com.example.plantbot.domain.PlantEnvironmentType;
import com.example.plantbot.domain.PlantGrowthStage;
import com.example.plantbot.domain.PlantPlacement;
import com.example.plantbot.domain.PlantType;
import com.example.plantbot.domain.RecommendationSource;
import com.example.plantbot.domain.SeedContainerType;
import com.example.plantbot.domain.SeedStage;
import com.example.plantbot.domain.SeedSubstrateType;
import com.example.plantbot.domain.SeedWateringMode;
import com.example.plantbot.domain.SunExposure;

import java.time.Instant;
import java.time.LocalDate;
import java.util.List;

public record PlantResponse(Long id,
                            String name,
                            PlantPlacement placement,
                            PlantCategory category,
                            PlantEnvironmentType wateringProfile,
                            String region,
                            PlantContainerType containerType,
                            Double containerVolumeLiters,
                            String cropType,
                            PlantGrowthStage growthStage,
                            SeedStage seedStage,
                            PlantEnvironmentType targetEnvironmentType,
                            SeedContainerType seedContainerType,
                            SeedSubstrateType seedSubstrateType,
                            LocalDate sowingDate,
                            Boolean underCover,
                            Boolean growLight,
                            Double germinationTemperatureC,
                            Integer expectedGerminationDaysMin,
                            Integer expectedGerminationDaysMax,
                            Integer recommendedCheckIntervalHours,
                            SeedWateringMode recommendedWateringMode,
                            String seedCareMode,
                            String seedSummary,
                            List<String> seedReasoning,
                            List<String> seedWarnings,
                            String seedCareSource,
                            List<String> seedActions,
                            Boolean greenhouse,
                            Boolean dripIrrigation,
                            Double potVolumeLiters,
                            Double outdoorAreaM2,
                            OutdoorSoilType outdoorSoilType,
                            SunExposure sunExposure,
                            Boolean mulched,
                            Boolean perennial,
                            Boolean winterDormancyEnabled,
                            LocalDate lastWateredDate,
                            Integer baseIntervalDays,
                            Integer preferredWaterMl,
                            LocalDate nextWateringDate,
                            Integer recommendedWaterMl,
                            Integer recommendedIntervalDays,
                            RecommendationSource recommendationSource,
                            String recommendationSummary,
                            Double confidenceScore,
                            Instant recommendationGeneratedAt,
                            PlantType type,
                            PlantAvatarResponse avatar,
                            String photoUrl,
                            Instant createdAt) {
}
